name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build with Docker
      run: |
        docker build -t winforms-app .

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: winforms-app
        path: ./out